#ifndef CONFIG_H
#define CONFIG_H

#define VERSION "0.11.4"
/* #undef WITH_BINLOG */
#define WITH_SSL

#if   defined(LIBMYSQL_VERSION)
#define MYSQL_VERSION_STR LIBMYSQL_VERSION
#elif defined(MARIADB_CLIENT_VERSION_STR)
#define MYSQL_VERSION_STR MARIADB_CLIENT_VERSION_STR
#elif defined(MYSQL_VERSION_NUMBER)
#define MYSQL_VERSION_STR MYSQL_VERSION_NUMBER
#else
#define MYSQL_VERSION_STR MYSQL_SERVER_VERSION
#endif

#endif
